# Generated by Django 5.2.17 on 2026-09-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='secret_header_value',
            field=models.CharField(blank=True, default='', max_length=768),
        ),
    ]
